// Code generated by vivgen from KDL. DO NOT EDIT.
package capabilities

import "encoding/json"

// GeneratedRegistry returns a map of all registered capability names to their JSON schemas.
func GeneratedRegistry() map[string]string {
	return map[string]string{
		"Browser_Form_Submit":          Browser_Form_SubmitSchema,
		"Browser_Link_List":            Browser_Link_ListSchema,
		"Browser_Page_GetTitle":        Browser_Page_GetTitleSchema,
		"Browser_Page_Read":            Browser_Page_ReadSchema,
		"Browser_Page_Screenshot":      Browser_Page_ScreenshotSchema,
		"Calendar_Event_Create":        Calendar_Event_CreateSchema,
		"Calendar_Event_List":          Calendar_Event_ListSchema,
		"Calendar_Event_Read":          Calendar_Event_ReadSchema,
		"Calendar_Slot_Find":           Calendar_Slot_FindSchema,
		"Code_Lint_Run":                Code_Lint_RunSchema,
		"Code_Script_Exec":             Code_Script_ExecSchema,
		"Code_Test_Run":                Code_Test_RunSchema,
		"Commerce_Order_Create":        Commerce_Order_CreateSchema,
		"Database_Query_Exec":          Database_Query_ExecSchema,
		"Database_Schema_Read":         Database_Schema_ReadSchema,
		"Database_Table_List":          Database_Table_ListSchema,
		"Document_Content_Append":      Document_Content_AppendSchema,
		"Document_Content_Read":        Document_Content_ReadSchema,
		"Document_Content_Replace":     Document_Content_ReplaceSchema,
		"Document_Doc_List":            Document_Doc_ListSchema,
		"Email_Message_Create":         Email_Message_CreateSchema,
		"Email_Message_List":           Email_Message_ListSchema,
		"Email_Message_Read":           Email_Message_ReadSchema,
		"Email_Message_Send":           Email_Message_SendSchema,
		"Filesystem_Dir_Create":        Filesystem_Dir_CreateSchema,
		"Filesystem_Dir_List":          Filesystem_Dir_ListSchema,
		"Filesystem_File_Delete":       Filesystem_File_DeleteSchema,
		"Filesystem_File_Move":         Filesystem_File_MoveSchema,
		"Filesystem_File_Read":         Filesystem_File_ReadSchema,
		"Filesystem_File_Write":        Filesystem_File_WriteSchema,
		"Media_Audio_Transcribe":       Media_Audio_TranscribeSchema,
		"Media_Image_Analyze":          Media_Image_AnalyzeSchema,
		"Memory_Fact_Delete":           Memory_Fact_DeleteSchema,
		"Memory_Fact_List":             Memory_Fact_ListSchema,
		"Memory_Fact_Search":           Memory_Fact_SearchSchema,
		"Memory_Fact_Store":            Memory_Fact_StoreSchema,
		"Messaging_Channel_List":       Messaging_Channel_ListSchema,
		"Messaging_Chat_Send":          Messaging_Chat_SendSchema,
		"Messaging_Message_List":       Messaging_Message_ListSchema,
		"Messaging_Sms_Send":           Messaging_Sms_SendSchema,
		"Search_Corpus_Query":          Search_Corpus_QuerySchema,
		"Search_Web_Query":             Search_Web_QuerySchema,
		"SmartHome_Device_Invoke":      SmartHome_Device_InvokeSchema,
		"Spreadsheet_Range_Read":       Spreadsheet_Range_ReadSchema,
		"Spreadsheet_Range_Update":     Spreadsheet_Range_UpdateSchema,
		"Spreadsheet_Row_Create":       Spreadsheet_Row_CreateSchema,
		"Spreadsheet_Sheet_List":       Spreadsheet_Sheet_ListSchema,
		"Swarm_Agent_List":             Swarm_Agent_ListSchema,
		"Swarm_Group_Send":             Swarm_Group_SendSchema,
		"Swarm_Message_Send":           Swarm_Message_SendSchema,
		"System_Process_Exec":          System_Process_ExecSchema,
		"System_Process_Kill":          System_Process_KillSchema,
		"System_Process_List":          System_Process_ListSchema,
		"VersionControl_Branch_Create": VersionControl_Branch_CreateSchema,
		"VersionControl_Branch_List":   VersionControl_Branch_ListSchema,
		"VersionControl_Commit_Create": VersionControl_Commit_CreateSchema,
		"VersionControl_Diff_Read":     VersionControl_Diff_ReadSchema,
		"VersionControl_Log_List":      VersionControl_Log_ListSchema,
		"VersionControl_Remote_Push":   VersionControl_Remote_PushSchema,
		"VersionControl_Status_Read":   VersionControl_Status_ReadSchema,
	}
}

// Browser_Form_SubmitSchema is the JSON Schema for Browser_Form_Submit.
const Browser_Form_SubmitSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Browser_Form_Submit",
  "description": "Fill fields in an HTML form and submit it",
  "type": "object",
  "properties": {
    "fields": {
      "description": "List of {selector, value} pairs to fill before submitting",
      "type": "array",
      "additionalProperties": false,
      "examples": [
        "[{\"selector\": \"#email\", \"value\": \"user@example.com\"}]"
      ]
    },
    "submit_selector": {
      "description": "CSS selector of the submit button; omits native form submit if absent",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "button[type=submit]"
      ]
    },
    "url": {
      "description": "URL of the page containing the form",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "https://example.com/login"
      ]
    }
  },
  "required": [
    "url",
    "fields"
  ],
  "additionalProperties": false
}`

// Browser_Form_Submit is the argument struct for the Browser_Form_Submit capability.
// Fill fields in an HTML form and submit it
type Browser_Form_Submit struct {
	URL            string            `json:"url"`                       // URL of the page containing the form
	Fields         []json.RawMessage `json:"fields"`                    // List of {selector, value} pairs to fill before submitting
	SubmitSelector string            `json:"submit_selector,omitempty"` // CSS selector of the submit button; omits native form submit if absent
}

// Browser_Link_ListSchema is the JSON Schema for Browser_Link_List.
const Browser_Link_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Browser_Link_List",
  "description": "Extract all hyperlinks from the current page or a specified URL",
  "type": "object",
  "properties": {
    "same_domain_only": {
      "description": "Filter results to links sharing the same domain as the source URL",
      "type": "boolean",
      "additionalProperties": false,
      "default": true
    },
    "url": {
      "description": "Fully-qualified URL to extract links from",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "https://example.com/blog"
      ]
    }
  },
  "required": [
    "url"
  ],
  "additionalProperties": false
}`

// Browser_Link_List is the argument struct for the Browser_Link_List capability.
// Extract all hyperlinks from the current page or a specified URL
type Browser_Link_List struct {
	URL            string `json:"url"`                        // Fully-qualified URL to extract links from
	SameDomainOnly bool   `json:"same_domain_only,omitempty"` // Filter results to links sharing the same domain as the source URL
}

// Browser_Page_GetTitleSchema is the JSON Schema for Browser_Page_GetTitle.
const Browser_Page_GetTitleSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Browser_Page_GetTitle",
  "description": "Return the page title, meta description, and canonical URL without full content extraction",
  "type": "object",
  "properties": {
    "url": {
      "description": "Fully-qualified URL to inspect",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "https://example.com"
      ]
    }
  },
  "required": [
    "url"
  ],
  "additionalProperties": false
}`

// Browser_Page_GetTitle is the argument struct for the Browser_Page_GetTitle capability.
// Return the page title, meta description, and canonical URL without full content extraction
type Browser_Page_GetTitle struct {
	URL string `json:"url"` // Fully-qualified URL to inspect
}

// Browser_Page_ReadSchema is the JSON Schema for Browser_Page_Read.
const Browser_Page_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Browser_Page_Read",
  "description": "Fetch the readable text content of a web page, stripped of markup, scripts, and boilerplate",
  "type": "object",
  "properties": {
    "timeout": {
      "description": "Maximum seconds to wait for page load before aborting",
      "type": "integer",
      "additionalProperties": false,
      "default": 30
    },
    "url": {
      "description": "Fully-qualified URL of the page to fetch",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "https://en.wikipedia.org/wiki/Go_(programming_language)"
      ]
    },
    "wait_for": {
      "description": "Page load event to wait for before extracting content",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "load",
        "domcontentloaded",
        "networkidle"
      ],
      "default": "networkidle"
    }
  },
  "required": [
    "url"
  ],
  "additionalProperties": false
}`

// Browser_Page_Read is the argument struct for the Browser_Page_Read capability.
// Fetch the readable text content of a web page, stripped of markup, scripts, and boilerplate
type Browser_Page_Read struct {
	URL     string `json:"url"`                // Fully-qualified URL of the page to fetch
	Timeout int    `json:"timeout,omitempty"`  // Maximum seconds to wait for page load before aborting
	WaitFor string `json:"wait_for,omitempty"` // Page load event to wait for before extracting content
}

// Browser_Page_ScreenshotSchema is the JSON Schema for Browser_Page_Screenshot.
const Browser_Page_ScreenshotSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Browser_Page_Screenshot",
  "description": "Capture a screenshot of a web page or a specific element",
  "type": "object",
  "properties": {
    "full_page": {
      "description": "Capture the full scrollable page, not just the visible viewport",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    },
    "selector": {
      "description": "CSS selector of the element to capture; omit for full page",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "#main-chart"
      ]
    },
    "url": {
      "description": "Fully-qualified URL to navigate to before capturing",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "https://example.com/dashboard"
      ]
    }
  },
  "required": [
    "url"
  ],
  "additionalProperties": false
}`

// Browser_Page_Screenshot is the argument struct for the Browser_Page_Screenshot capability.
// Capture a screenshot of a web page or a specific element
type Browser_Page_Screenshot struct {
	URL      string `json:"url"`                 // Fully-qualified URL to navigate to before capturing
	Selector string `json:"selector,omitempty"`  // CSS selector of the element to capture; omit for full page
	FullPage bool   `json:"full_page,omitempty"` // Capture the full scrollable page, not just the visible viewport
}

// Calendar_Event_CreateSchema is the JSON Schema for Calendar_Event_Create.
const Calendar_Event_CreateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Calendar_Event_Create",
  "description": "Create a new calendar event",
  "type": "object",
  "properties": {
    "attendees": {
      "description": "Email addresses of attendees to invite",
      "type": "array",
      "additionalProperties": false
    },
    "description": {
      "description": "Event body / agenda",
      "type": "string",
      "additionalProperties": false
    },
    "end": {
      "description": "End datetime in ISO8601 format with timezone",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "2026-03-25T11:00:00+01:00"
      ]
    },
    "location": {
      "description": "Location or video call link",
      "type": "string",
      "additionalProperties": false
    },
    "start": {
      "description": "Start datetime in ISO8601 format with timezone",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "2026-03-25T10:00:00+01:00"
      ]
    },
    "title": {
      "description": "Event title",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "Sprint planning"
      ]
    }
  },
  "required": [
    "title",
    "start",
    "end"
  ],
  "additionalProperties": false
}`

// Calendar_Event_Create is the argument struct for the Calendar_Event_Create capability.
// Create a new calendar event
type Calendar_Event_Create struct {
	Title       string   `json:"title"`                 // Event title
	Start       string   `json:"start"`                 // Start datetime in ISO8601 format with timezone
	End         string   `json:"end"`                   // End datetime in ISO8601 format with timezone
	Attendees   []string `json:"attendees,omitempty"`   // Email addresses of attendees to invite
	Location    string   `json:"location,omitempty"`    // Location or video call link
	Description string   `json:"description,omitempty"` // Event body / agenda
}

// Calendar_Event_ListSchema is the JSON Schema for Calendar_Event_List.
const Calendar_Event_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Calendar_Event_List",
  "description": "List calendar events within a time range",
  "type": "object",
  "properties": {
    "calendar_id": {
      "description": "Calendar identifier; defaults to the primary calendar",
      "type": "string",
      "additionalProperties": false,
      "default": "primary"
    },
    "end": {
      "description": "Range end datetime in ISO8601 format",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "2026-03-27T17:00:00Z"
      ]
    },
    "start": {
      "description": "Range start datetime in ISO8601 format",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "2026-03-20T09:00:00Z"
      ]
    }
  },
  "required": [
    "start",
    "end"
  ],
  "additionalProperties": false
}`

// Calendar_Event_List is the argument struct for the Calendar_Event_List capability.
// List calendar events within a time range
type Calendar_Event_List struct {
	Start      string `json:"start"`                 // Range start datetime in ISO8601 format
	End        string `json:"end"`                   // Range end datetime in ISO8601 format
	CalendarId string `json:"calendar_id,omitempty"` // Calendar identifier; defaults to the primary calendar
}

// Calendar_Event_ReadSchema is the JSON Schema for Calendar_Event_Read.
const Calendar_Event_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Calendar_Event_Read",
  "description": "Read full details of a single calendar event",
  "type": "object",
  "properties": {
    "event_id": {
      "description": "Event ID from Calendar_Event_List",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "event_id"
  ],
  "additionalProperties": false
}`

// Calendar_Event_Read is the argument struct for the Calendar_Event_Read capability.
// Read full details of a single calendar event
type Calendar_Event_Read struct {
	EventId string `json:"event_id"` // Event ID from Calendar_Event_List
}

// Calendar_Slot_FindSchema is the JSON Schema for Calendar_Slot_Find.
const Calendar_Slot_FindSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Calendar_Slot_Find",
  "description": "Find free time slots across one or more attendees' calendars",
  "type": "object",
  "properties": {
    "attendees": {
      "description": "Email addresses to check availability for",
      "type": "array",
      "additionalProperties": false
    },
    "duration_minutes": {
      "description": "Required meeting duration in minutes",
      "type": "integer",
      "additionalProperties": false,
      "examples": [
        "60"
      ]
    },
    "window_end": {
      "description": "End of the search window in ISO8601",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "2026-03-28T00:00:00Z"
      ]
    },
    "window_start": {
      "description": "Start of the search window in ISO8601",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "2026-03-24T00:00:00Z"
      ]
    },
    "working_hours_only": {
      "description": "Restrict results to 09:00–18:00 local time of the organiser",
      "type": "boolean",
      "additionalProperties": false,
      "default": true
    }
  },
  "required": [
    "attendees",
    "duration_minutes",
    "window_start",
    "window_end"
  ],
  "additionalProperties": false
}`

// Calendar_Slot_Find is the argument struct for the Calendar_Slot_Find capability.
// Find free time slots across one or more attendees' calendars
type Calendar_Slot_Find struct {
	Attendees        []string `json:"attendees"`                    // Email addresses to check availability for
	DurationMinutes  int      `json:"duration_minutes"`             // Required meeting duration in minutes
	WindowStart      string   `json:"window_start"`                 // Start of the search window in ISO8601
	WindowEnd        string   `json:"window_end"`                   // End of the search window in ISO8601
	WorkingHoursOnly bool     `json:"working_hours_only,omitempty"` // Restrict results to 09:00–18:00 local time of the organiser
}

// Code_Lint_RunSchema is the JSON Schema for Code_Lint_Run.
const Code_Lint_RunSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Code_Lint_Run",
  "description": "Run a linter and return findings",
  "type": "object",
  "properties": {
    "linter": {
      "description": "Linter to invoke",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "golangci-lint",
        "ruff",
        "eslint",
        "rubocop",
        "clippy"
      ]
    },
    "path": {
      "description": "Workspace-relative path to lint",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "required": [
    "linter"
  ],
  "additionalProperties": false
}`

// Code_Lint_Run is the argument struct for the Code_Lint_Run capability.
// Run a linter and return findings
type Code_Lint_Run struct {
	Linter string `json:"linter"`         // Linter to invoke
	Path   string `json:"path,omitempty"` // Workspace-relative path to lint
}

// Code_Script_ExecSchema is the JSON Schema for Code_Script_Exec.
const Code_Script_ExecSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Code_Script_Exec",
  "description": "Execute a script or shell command inside the agent jail and return its output",
  "type": "object",
  "properties": {
    "interpreter": {
      "description": "The interpreter to use",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "bash",
        "python3",
        "node",
        "ruby"
      ]
    },
    "script": {
      "description": "The script body to execute",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "echo hello \u0026\u0026 ls -la"
      ]
    },
    "timeout": {
      "description": "Maximum execution time in seconds",
      "type": "integer",
      "additionalProperties": false,
      "default": 30
    }
  },
  "required": [
    "interpreter",
    "script"
  ],
  "additionalProperties": false
}`

// Code_Script_Exec is the argument struct for the Code_Script_Exec capability.
// Execute a script or shell command inside the agent jail and return its output
type Code_Script_Exec struct {
	Interpreter string `json:"interpreter"`       // The interpreter to use
	Script      string `json:"script"`            // The script body to execute
	Timeout     int    `json:"timeout,omitempty"` // Maximum execution time in seconds
}

// Code_Test_RunSchema is the JSON Schema for Code_Test_Run.
const Code_Test_RunSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Code_Test_Run",
  "description": "Run a project's test suite and return results",
  "type": "object",
  "properties": {
    "filter": {
      "description": "Pattern to filter which tests run",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "TestSwitchboard"
      ]
    },
    "framework": {
      "description": "Test framework to invoke",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "go-test",
        "pytest",
        "jest",
        "rspec",
        "cargo-test"
      ]
    },
    "path": {
      "description": "Workspace-relative path to run tests from",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "required": [
    "framework"
  ],
  "additionalProperties": false
}`

// Code_Test_Run is the argument struct for the Code_Test_Run capability.
// Run a project's test suite and return results
type Code_Test_Run struct {
	Framework string `json:"framework"`        // Test framework to invoke
	Path      string `json:"path,omitempty"`   // Workspace-relative path to run tests from
	Filter    string `json:"filter,omitempty"` // Pattern to filter which tests run
}

// Commerce_Order_CreateSchema is the JSON Schema for Commerce_Order_Create.
const Commerce_Order_CreateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Commerce_Order_Create",
  "description": "Place an order with a configured commerce provider (e.g. Shopify, Amazon). Requires explicit operator approval by default due to critical risk level.",
  "type": "object",
  "properties": {
    "confirm": {
      "description": "Must be explicitly set to true; prevents accidental order placement",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    },
    "quantity": {
      "description": "Number of units to order",
      "type": "integer",
      "additionalProperties": false
    },
    "shipping_address_id": {
      "description": "ID of a pre-registered shipping address in the operator vault",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "addr_home"
      ]
    },
    "sku": {
      "description": "Product SKU or provider item ID to purchase",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "B08N5WRWNW"
      ]
    }
  },
  "required": [
    "sku",
    "quantity",
    "shipping_address_id",
    "confirm"
  ],
  "additionalProperties": false
}`

// Commerce_Order_Create is the argument struct for the Commerce_Order_Create capability.
// Place an order with a configured commerce provider (e.g. Shopify, Amazon). Requires explicit operator approval by default due to critical risk level.
type Commerce_Order_Create struct {
	Sku               string `json:"sku"`                 // Product SKU or provider item ID to purchase
	Quantity          int    `json:"quantity"`            // Number of units to order
	ShippingAddressId string `json:"shipping_address_id"` // ID of a pre-registered shipping address in the operator vault
	Confirm           bool   `json:"confirm"`             // Must be explicitly set to true; prevents accidental order placement
}

// Database_Query_ExecSchema is the JSON Schema for Database_Query_Exec.
const Database_Query_ExecSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Database_Query_Exec",
  "description": "Execute a read-only SQL query against a permitted data source",
  "type": "object",
  "properties": {
    "max_rows": {
      "description": "Maximum rows to return",
      "type": "integer",
      "additionalProperties": false,
      "default": 100
    },
    "query": {
      "description": "SQL SELECT statement to execute; INSERT/UPDATE/DELETE are rejected",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "SELECT user_id, count(*) FROM events GROUP BY user_id LIMIT 100"
      ]
    },
    "source_id": {
      "description": "Data source identifier from agent.kdl data.sources",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "analytics-db"
      ]
    }
  },
  "required": [
    "source_id",
    "query"
  ],
  "additionalProperties": false
}`

// Database_Query_Exec is the argument struct for the Database_Query_Exec capability.
// Execute a read-only SQL query against a permitted data source
type Database_Query_Exec struct {
	SourceId string `json:"source_id"`          // Data source identifier from agent.kdl data.sources
	Query    string `json:"query"`              // SQL SELECT statement to execute; INSERT/UPDATE/DELETE are rejected
	MaxRows  int    `json:"max_rows,omitempty"` // Maximum rows to return
}

// Database_Schema_ReadSchema is the JSON Schema for Database_Schema_Read.
const Database_Schema_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Database_Schema_Read",
  "description": "Read the schema of a specific table or collection",
  "type": "object",
  "properties": {
    "source_id": {
      "description": "Data source identifier from agent.kdl data.sources",
      "type": "string",
      "additionalProperties": false
    },
    "table": {
      "description": "Table or collection name",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "events"
      ]
    }
  },
  "required": [
    "source_id",
    "table"
  ],
  "additionalProperties": false
}`

// Database_Schema_Read is the argument struct for the Database_Schema_Read capability.
// Read the schema of a specific table or collection
type Database_Schema_Read struct {
	SourceId string `json:"source_id"` // Data source identifier from agent.kdl data.sources
	Table    string `json:"table"`     // Table or collection name
}

// Database_Table_ListSchema is the JSON Schema for Database_Table_List.
const Database_Table_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Database_Table_List",
  "description": "List tables or collections in a data source",
  "type": "object",
  "properties": {
    "source_id": {
      "description": "Data source identifier from agent.kdl data.sources",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "source_id"
  ],
  "additionalProperties": false
}`

// Database_Table_List is the argument struct for the Database_Table_List capability.
// List tables or collections in a data source
type Database_Table_List struct {
	SourceId string `json:"source_id"` // Data source identifier from agent.kdl data.sources
}

// Document_Content_AppendSchema is the JSON Schema for Document_Content_Append.
const Document_Content_AppendSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Document_Content_Append",
  "description": "Append text to the end of a document",
  "type": "object",
  "properties": {
    "content": {
      "description": "Markdown text to append",
      "type": "string",
      "additionalProperties": false
    },
    "document_id": {
      "description": "Provider document identifier",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "document_id",
    "content"
  ],
  "additionalProperties": false
}`

// Document_Content_Append is the argument struct for the Document_Content_Append capability.
// Append text to the end of a document
type Document_Content_Append struct {
	DocumentId string `json:"document_id"` // Provider document identifier
	Content    string `json:"content"`     // Markdown text to append
}

// Document_Content_ReadSchema is the JSON Schema for Document_Content_Read.
const Document_Content_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Document_Content_Read",
  "description": "Read a document's full content as clean markdown; strips comments and change history",
  "type": "object",
  "properties": {
    "document_id": {
      "description": "Provider document identifier",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "document_id"
  ],
  "additionalProperties": false
}`

// Document_Content_Read is the argument struct for the Document_Content_Read capability.
// Read a document's full content as clean markdown; strips comments and change history
type Document_Content_Read struct {
	DocumentId string `json:"document_id"` // Provider document identifier
}

// Document_Content_ReplaceSchema is the JSON Schema for Document_Content_Replace.
const Document_Content_ReplaceSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Document_Content_Replace",
  "description": "Replace a specific section of a document identified by a heading",
  "type": "object",
  "properties": {
    "content": {
      "description": "Replacement markdown content",
      "type": "string",
      "additionalProperties": false
    },
    "document_id": {
      "description": "Provider document identifier",
      "type": "string",
      "additionalProperties": false
    },
    "heading": {
      "description": "Exact text of the heading whose section should be replaced",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "## Summary"
      ]
    }
  },
  "required": [
    "document_id",
    "heading",
    "content"
  ],
  "additionalProperties": false
}`

// Document_Content_Replace is the argument struct for the Document_Content_Replace capability.
// Replace a specific section of a document identified by a heading
type Document_Content_Replace struct {
	DocumentId string `json:"document_id"` // Provider document identifier
	Heading    string `json:"heading"`     // Exact text of the heading whose section should be replaced
	Content    string `json:"content"`     // Replacement markdown content
}

// Document_Doc_ListSchema is the JSON Schema for Document_Doc_List.
const Document_Doc_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Document_Doc_List",
  "description": "List documents accessible to the agent's credential",
  "type": "object",
  "properties": {
    "max_results": {
      "type": "integer",
      "additionalProperties": false,
      "default": 20
    },
    "query": {
      "description": "Title or full-text search filter",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "Q1 report"
      ]
    }
  },
  "additionalProperties": false
}`

// Document_Doc_List is the argument struct for the Document_Doc_List capability.
// List documents accessible to the agent's credential
type Document_Doc_List struct {
	Query      string `json:"query,omitempty"` // Title or full-text search filter
	MaxResults int    `json:"max_results,omitempty"`
}

// Email_Message_CreateSchema is the JSON Schema for Email_Message_Create.
const Email_Message_CreateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Email_Message_Create",
  "description": "Create an email draft without sending it",
  "type": "object",
  "properties": {
    "body": {
      "description": "Email body in plain text or markdown",
      "type": "string",
      "additionalProperties": false
    },
    "cc": {
      "description": "CC recipient addresses",
      "type": "array",
      "additionalProperties": false
    },
    "subject": {
      "description": "Email subject line",
      "type": "string",
      "additionalProperties": false
    },
    "to": {
      "description": "Recipient email addresses",
      "type": "array",
      "additionalProperties": false,
      "examples": [
        "[\"colleague@example.com\"]"
      ]
    }
  },
  "required": [
    "to",
    "subject",
    "body"
  ],
  "additionalProperties": false
}`

// Email_Message_Create is the argument struct for the Email_Message_Create capability.
// Create an email draft without sending it
type Email_Message_Create struct {
	To      []string `json:"to"`           // Recipient email addresses
	Subject string   `json:"subject"`      // Email subject line
	Body    string   `json:"body"`         // Email body in plain text or markdown
	Cc      []string `json:"cc,omitempty"` // CC recipient addresses
}

// Email_Message_ListSchema is the JSON Schema for Email_Message_List.
const Email_Message_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Email_Message_List",
  "description": "List email messages matching a filter; returns metadata only, not bodies",
  "type": "object",
  "properties": {
    "folder": {
      "description": "Folder to list messages from",
      "type": "string",
      "additionalProperties": false,
      "default": "inbox",
      "examples": [
        "inbox"
      ]
    },
    "max_results": {
      "description": "Maximum messages to return",
      "type": "integer",
      "additionalProperties": false,
      "default": 20
    },
    "query": {
      "description": "Provider search query to filter results",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "from:boss@example.com subject:urgent"
      ]
    },
    "unread_only": {
      "description": "Return only unread messages",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    }
  },
  "additionalProperties": false
}`

// Email_Message_List is the argument struct for the Email_Message_List capability.
// List email messages matching a filter; returns metadata only, not bodies
type Email_Message_List struct {
	Folder     string `json:"folder,omitempty"`      // Folder to list messages from
	UnreadOnly bool   `json:"unread_only,omitempty"` // Return only unread messages
	MaxResults int    `json:"max_results,omitempty"` // Maximum messages to return
	Query      string `json:"query,omitempty"`       // Provider search query to filter results
}

// Email_Message_ReadSchema is the JSON Schema for Email_Message_Read.
const Email_Message_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Email_Message_Read",
  "description": "Read the body and headers of a specific email message",
  "type": "object",
  "properties": {
    "message_id": {
      "description": "Provider message ID from Mail_Message_List",
      "type": "string",
      "additionalProperties": false
    },
    "strip_tracking": {
      "description": "Remove tracking pixels and link redirects from the body",
      "type": "boolean",
      "additionalProperties": false,
      "default": true
    }
  },
  "required": [
    "message_id"
  ],
  "additionalProperties": false
}`

// Email_Message_Read is the argument struct for the Email_Message_Read capability.
// Read the body and headers of a specific email message
type Email_Message_Read struct {
	MessageId     string `json:"message_id"`               // Provider message ID from Mail_Message_List
	StripTracking bool   `json:"strip_tracking,omitempty"` // Remove tracking pixels and link redirects from the body
}

// Email_Message_SendSchema is the JSON Schema for Email_Message_Send.
const Email_Message_SendSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Email_Message_Send",
  "description": "Send an existing draft message",
  "type": "object",
  "properties": {
    "draft_id": {
      "description": "Draft ID from Mail_Message_Create",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "draft_id"
  ],
  "additionalProperties": false
}`

// Email_Message_Send is the argument struct for the Email_Message_Send capability.
// Send an existing draft message
type Email_Message_Send struct {
	DraftId string `json:"draft_id"` // Draft ID from Mail_Message_Create
}

// Filesystem_Dir_CreateSchema is the JSON Schema for Filesystem_Dir_Create.
const Filesystem_Dir_CreateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Filesystem_Dir_Create",
  "description": "Create a directory (and any missing parents) in the agent workspace",
  "type": "object",
  "properties": {
    "path": {
      "description": "Workspace-relative directory path to create",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "output/charts"
      ]
    }
  },
  "required": [
    "path"
  ],
  "additionalProperties": false
}`

// Filesystem_Dir_Create is the argument struct for the Filesystem_Dir_Create capability.
// Create a directory (and any missing parents) in the agent workspace
type Filesystem_Dir_Create struct {
	Path string `json:"path"` // Workspace-relative directory path to create
}

// Filesystem_Dir_ListSchema is the JSON Schema for Filesystem_Dir_List.
const Filesystem_Dir_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Filesystem_Dir_List",
  "description": "List the contents of a directory in the agent workspace",
  "type": "object",
  "properties": {
    "path": {
      "description": "Workspace-relative directory path to list",
      "type": "string",
      "additionalProperties": false,
      "default": ".",
      "examples": [
        "output"
      ]
    },
    "recursive": {
      "description": "Recurse into subdirectories",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    }
  },
  "additionalProperties": false
}`

// Filesystem_Dir_List is the argument struct for the Filesystem_Dir_List capability.
// List the contents of a directory in the agent workspace
type Filesystem_Dir_List struct {
	Path      string `json:"path,omitempty"`      // Workspace-relative directory path to list
	Recursive bool   `json:"recursive,omitempty"` // Recurse into subdirectories
}

// Filesystem_File_DeleteSchema is the JSON Schema for Filesystem_File_Delete.
const Filesystem_File_DeleteSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Filesystem_File_Delete",
  "description": "Delete a file from the agent workspace",
  "type": "object",
  "properties": {
    "path": {
      "description": "Workspace-relative path of the file to delete",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "tmp/scratch.txt"
      ]
    }
  },
  "required": [
    "path"
  ],
  "additionalProperties": false
}`

// Filesystem_File_Delete is the argument struct for the Filesystem_File_Delete capability.
// Delete a file from the agent workspace
type Filesystem_File_Delete struct {
	Path string `json:"path"` // Workspace-relative path of the file to delete
}

// Filesystem_File_MoveSchema is the JSON Schema for Filesystem_File_Move.
const Filesystem_File_MoveSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Filesystem_File_Move",
  "description": "Move or rename a file within the agent workspace",
  "type": "object",
  "properties": {
    "dst": {
      "description": "Workspace-relative destination path",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "output/report.md"
      ]
    },
    "src": {
      "description": "Workspace-relative source path",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "draft/report.md"
      ]
    }
  },
  "required": [
    "src",
    "dst"
  ],
  "additionalProperties": false
}`

// Filesystem_File_Move is the argument struct for the Filesystem_File_Move capability.
// Move or rename a file within the agent workspace
type Filesystem_File_Move struct {
	Src string `json:"src"` // Workspace-relative source path
	Dst string `json:"dst"` // Workspace-relative destination path
}

// Filesystem_File_ReadSchema is the JSON Schema for Filesystem_File_Read.
const Filesystem_File_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Filesystem_File_Read",
  "description": "Read the contents of a file in the agent workspace",
  "type": "object",
  "properties": {
    "encoding": {
      "description": "Text encoding; use 'base64' for binary files",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "utf-8",
        "base64"
      ],
      "default": "utf-8"
    },
    "path": {
      "description": "Workspace-relative path to the file",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "output/report.md"
      ]
    }
  },
  "required": [
    "path"
  ],
  "additionalProperties": false
}`

// Filesystem_File_Read is the argument struct for the Filesystem_File_Read capability.
// Read the contents of a file in the agent workspace
type Filesystem_File_Read struct {
	Path     string `json:"path"`               // Workspace-relative path to the file
	Encoding string `json:"encoding,omitempty"` // Text encoding; use 'base64' for binary files
}

// Filesystem_File_WriteSchema is the JSON Schema for Filesystem_File_Write.
const Filesystem_File_WriteSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Filesystem_File_Write",
  "description": "Write or overwrite a file in the agent workspace",
  "type": "object",
  "properties": {
    "append": {
      "description": "If true, append to the file instead of overwriting",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    },
    "content": {
      "description": "Content to write; use base64 encoding for binary data",
      "type": "string",
      "additionalProperties": false
    },
    "encoding": {
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "utf-8",
        "base64"
      ],
      "default": "utf-8"
    },
    "path": {
      "description": "Workspace-relative path; intermediate directories are created if absent",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "output/report.md"
      ]
    }
  },
  "required": [
    "path",
    "content"
  ],
  "additionalProperties": false
}`

// Filesystem_File_Write is the argument struct for the Filesystem_File_Write capability.
// Write or overwrite a file in the agent workspace
type Filesystem_File_Write struct {
	Path     string `json:"path"`             // Workspace-relative path; intermediate directories are created if absent
	Content  string `json:"content"`          // Content to write; use base64 encoding for binary data
	Append   bool   `json:"append,omitempty"` // If true, append to the file instead of overwriting
	Encoding string `json:"encoding,omitempty"`
}

// Media_Audio_TranscribeSchema is the JSON Schema for Media_Audio_Transcribe.
const Media_Audio_TranscribeSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Media_Audio_Transcribe",
  "description": "Transcribe an audio file to text",
  "type": "object",
  "properties": {
    "language": {
      "description": "BCP-47 language code hint; omit for auto-detection",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "en-US"
      ]
    },
    "path": {
      "description": "Workspace-relative path to the audio file (mp3, wav, m4a)",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "recordings/meeting.mp3"
      ]
    }
  },
  "required": [
    "path"
  ],
  "additionalProperties": false
}`

// Media_Audio_Transcribe is the argument struct for the Media_Audio_Transcribe capability.
// Transcribe an audio file to text
type Media_Audio_Transcribe struct {
	Path     string `json:"path"`               // Workspace-relative path to the audio file (mp3, wav, m4a)
	Language string `json:"language,omitempty"` // BCP-47 language code hint; omit for auto-detection
}

// Media_Image_AnalyzeSchema is the JSON Schema for Media_Image_Analyze.
const Media_Image_AnalyzeSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Media_Image_Analyze",
  "description": "Describe or answer questions about an image using a vision model",
  "type": "object",
  "properties": {
    "prompt": {
      "description": "Instruction to the vision model",
      "type": "string",
      "additionalProperties": false,
      "default": "Describe this image in detail",
      "examples": [
        "What is the trend shown in this chart?"
      ]
    },
    "source": {
      "description": "Workspace-relative file path or a data URI (base64 PNG/JPEG)",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "output/chart.png"
      ]
    }
  },
  "required": [
    "source"
  ],
  "additionalProperties": false
}`

// Media_Image_Analyze is the argument struct for the Media_Image_Analyze capability.
// Describe or answer questions about an image using a vision model
type Media_Image_Analyze struct {
	Source string `json:"source"`           // Workspace-relative file path or a data URI (base64 PNG/JPEG)
	Prompt string `json:"prompt,omitempty"` // Instruction to the vision model
}

// Memory_Fact_DeleteSchema is the JSON Schema for Memory_Fact_Delete.
const Memory_Fact_DeleteSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Memory_Fact_Delete",
  "description": "Delete a stored memory by key",
  "type": "object",
  "properties": {
    "key": {
      "description": "Key of the memory to delete",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "key"
  ],
  "additionalProperties": false
}`

// Memory_Fact_Delete is the argument struct for the Memory_Fact_Delete capability.
// Delete a stored memory by key
type Memory_Fact_Delete struct {
	Key string `json:"key"` // Key of the memory to delete
}

// Memory_Fact_ListSchema is the JSON Schema for Memory_Fact_List.
const Memory_Fact_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Memory_Fact_List",
  "description": "List all stored memories, optionally filtered by tag",
  "type": "object",
  "properties": {
    "max_results": {
      "type": "integer",
      "additionalProperties": false,
      "default": 50
    },
    "tag": {
      "description": "Filter by this tag; omit to list all",
      "type": "string",
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}`

// Memory_Fact_List is the argument struct for the Memory_Fact_List capability.
// List all stored memories, optionally filtered by tag
type Memory_Fact_List struct {
	Tag        string `json:"tag,omitempty"` // Filter by this tag; omit to list all
	MaxResults int    `json:"max_results,omitempty"`
}

// Memory_Fact_SearchSchema is the JSON Schema for Memory_Fact_Search.
const Memory_Fact_SearchSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Memory_Fact_Search",
  "description": "Semantic search over the agent's stored memories",
  "type": "object",
  "properties": {
    "max_results": {
      "type": "integer",
      "additionalProperties": false,
      "default": 5
    },
    "query": {
      "description": "Natural language query to find relevant memories",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "what does the user prefer for code style?"
      ]
    }
  },
  "required": [
    "query"
  ],
  "additionalProperties": false
}`

// Memory_Fact_Search is the argument struct for the Memory_Fact_Search capability.
// Semantic search over the agent's stored memories
type Memory_Fact_Search struct {
	Query      string `json:"query"` // Natural language query to find relevant memories
	MaxResults int    `json:"max_results,omitempty"`
}

// Memory_Fact_StoreSchema is the JSON Schema for Memory_Fact_Store.
const Memory_Fact_StoreSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Memory_Fact_Store",
  "description": "Store a fact or note in the agent's persistent memory",
  "type": "object",
  "properties": {
    "key": {
      "description": "Unique key for retrieval; use a descriptive slug",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "user-preferred-language"
      ]
    },
    "tags": {
      "description": "Categorical tags for filtered retrieval",
      "type": "array",
      "additionalProperties": false,
      "examples": [
        "[\"preference\", \"user\"]"
      ]
    },
    "value": {
      "description": "The fact or content to remember",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "key",
    "value"
  ],
  "additionalProperties": false
}`

// Memory_Fact_Store is the argument struct for the Memory_Fact_Store capability.
// Store a fact or note in the agent's persistent memory
type Memory_Fact_Store struct {
	Key   string   `json:"key"`            // Unique key for retrieval; use a descriptive slug
	Value string   `json:"value"`          // The fact or content to remember
	Tags  []string `json:"tags,omitempty"` // Categorical tags for filtered retrieval
}

// Messaging_Channel_ListSchema is the JSON Schema for Messaging_Channel_List.
const Messaging_Channel_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Messaging_Channel_List",
  "description": "List channels the credential has access to",
  "type": "object",
  "properties": {
    "include_private": {
      "description": "Include private channels the credential is a member of",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    }
  },
  "additionalProperties": false
}`

// Messaging_Channel_List is the argument struct for the Messaging_Channel_List capability.
// List channels the credential has access to
type Messaging_Channel_List struct {
	IncludePrivate bool `json:"include_private,omitempty"` // Include private channels the credential is a member of
}

// Messaging_Chat_SendSchema is the JSON Schema for Messaging_Chat_Send.
const Messaging_Chat_SendSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Messaging_Chat_Send",
  "description": "Send a message to a channel or user",
  "type": "object",
  "properties": {
    "destination": {
      "description": "Channel name (#channel) or user handle (@user)",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "#engineering"
      ]
    },
    "text": {
      "description": "Message body in plain text or provider markdown",
      "type": "string",
      "additionalProperties": false
    },
    "thread_ts": {
      "description": "Thread timestamp to reply in a thread rather than the main channel",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "destination",
    "text"
  ],
  "additionalProperties": false
}`

// Messaging_Chat_Send is the argument struct for the Messaging_Chat_Send capability.
// Send a message to a channel or user
type Messaging_Chat_Send struct {
	Destination string `json:"destination"`         // Channel name (#channel) or user handle (@user)
	Text        string `json:"text"`                // Message body in plain text or provider markdown
	ThreadTs    string `json:"thread_ts,omitempty"` // Thread timestamp to reply in a thread rather than the main channel
}

// Messaging_Message_ListSchema is the JSON Schema for Messaging_Message_List.
const Messaging_Message_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Messaging_Message_List",
  "description": "List recent messages from a channel",
  "type": "object",
  "properties": {
    "channel": {
      "description": "Channel identifier or name",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "#engineering"
      ]
    },
    "max_results": {
      "type": "integer",
      "additionalProperties": false,
      "default": 20
    },
    "since": {
      "description": "Return only messages after this ISO8601 timestamp",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "channel"
  ],
  "additionalProperties": false
}`

// Messaging_Message_List is the argument struct for the Messaging_Message_List capability.
// List recent messages from a channel
type Messaging_Message_List struct {
	Channel    string `json:"channel"` // Channel identifier or name
	MaxResults int    `json:"max_results,omitempty"`
	Since      string `json:"since,omitempty"` // Return only messages after this ISO8601 timestamp
}

// Messaging_Sms_SendSchema is the JSON Schema for Messaging_Sms_Send.
const Messaging_Sms_SendSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Messaging_Sms_Send",
  "description": "Send a message to a contact via the configured messaging provider (e.g. WhatsApp, SMS, Signal)",
  "type": "object",
  "properties": {
    "body": {
      "description": "Plain-text message body",
      "type": "string",
      "additionalProperties": false
    },
    "provider": {
      "description": "Messaging provider to use",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "whatsapp",
        "sms",
        "signal"
      ],
      "default": "whatsapp"
    },
    "to": {
      "description": "Recipient phone number (E.164) or provider contact ID",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "+14155552671"
      ]
    }
  },
  "required": [
    "to",
    "body"
  ],
  "additionalProperties": false
}`

// Messaging_Sms_Send is the argument struct for the Messaging_Sms_Send capability.
// Send a message to a contact via the configured messaging provider (e.g. WhatsApp, SMS, Signal)
type Messaging_Sms_Send struct {
	To       string `json:"to"`                 // Recipient phone number (E.164) or provider contact ID
	Body     string `json:"body"`               // Plain-text message body
	Provider string `json:"provider,omitempty"` // Messaging provider to use
}

// Search_Corpus_QuerySchema is the JSON Schema for Search_Corpus_Query.
const Search_Corpus_QuerySchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Search_Corpus_Query",
  "description": "Semantic similarity search over an indexed document corpus",
  "type": "object",
  "properties": {
    "corpus_id": {
      "description": "Identifier of the indexed corpus to search",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "internal-docs-2025"
      ]
    },
    "max_results": {
      "description": "Maximum number of results to return",
      "type": "integer",
      "additionalProperties": false,
      "default": 5
    },
    "query": {
      "description": "Natural language query to search for semantically similar content",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "agent credential isolation patterns"
      ]
    }
  },
  "required": [
    "query",
    "corpus_id"
  ],
  "additionalProperties": false
}`

// Search_Corpus_Query is the argument struct for the Search_Corpus_Query capability.
// Semantic similarity search over an indexed document corpus
type Search_Corpus_Query struct {
	Query      string `json:"query"`                 // Natural language query to search for semantically similar content
	CorpusId   string `json:"corpus_id"`             // Identifier of the indexed corpus to search
	MaxResults int    `json:"max_results,omitempty"` // Maximum number of results to return
}

// Search_Web_QuerySchema is the JSON Schema for Search_Web_Query.
const Search_Web_QuerySchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Search_Web_Query",
  "description": "Execute a web search and return ranked result summaries; does not load full pages",
  "type": "object",
  "properties": {
    "date_after": {
      "description": "Restrict results to pages published after this date (ISO8601)",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "2025-01-01"
      ]
    },
    "max_results": {
      "description": "Maximum number of results to return",
      "type": "integer",
      "additionalProperties": false,
      "default": 10
    },
    "query": {
      "description": "Natural language or keyword search query",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "systemd-nspawn user namespacing security"
      ]
    }
  },
  "required": [
    "query"
  ],
  "additionalProperties": false
}`

// Search_Web_Query is the argument struct for the Search_Web_Query capability.
// Execute a web search and return ranked result summaries; does not load full pages
type Search_Web_Query struct {
	Query      string `json:"query"`                 // Natural language or keyword search query
	MaxResults int    `json:"max_results,omitempty"` // Maximum number of results to return
	DateAfter  string `json:"date_after,omitempty"`  // Restrict results to pages published after this date (ISO8601)
}

// SmartHome_Device_InvokeSchema is the JSON Schema for SmartHome_Device_Invoke.
const SmartHome_Device_InvokeSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "SmartHome_Device_Invoke",
  "description": "Invoke an action on a smart home device via the configured hub (e.g. Home Assistant, Google Home)",
  "type": "object",
  "properties": {
    "action": {
      "description": "Action to invoke on the device",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "on",
        "off",
        "toggle",
        "set"
      ]
    },
    "device_id": {
      "description": "Hub-assigned device identifier",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "light.living_room_main"
      ]
    },
    "value": {
      "description": "Parameter for 'set' actions, e.g. brightness percentage or target temperature",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "72"
      ]
    }
  },
  "required": [
    "device_id",
    "action"
  ],
  "additionalProperties": false
}`

// SmartHome_Device_Invoke is the argument struct for the SmartHome_Device_Invoke capability.
// Invoke an action on a smart home device via the configured hub (e.g. Home Assistant, Google Home)
type SmartHome_Device_Invoke struct {
	DeviceId string `json:"device_id"`       // Hub-assigned device identifier
	Action   string `json:"action"`          // Action to invoke on the device
	Value    string `json:"value,omitempty"` // Parameter for 'set' actions, e.g. brightness percentage or target temperature
}

// Spreadsheet_Range_ReadSchema is the JSON Schema for Spreadsheet_Range_Read.
const Spreadsheet_Range_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Spreadsheet_Range_Read",
  "description": "Read a cell range from a spreadsheet; returns raw values only, no formatting",
  "type": "object",
  "properties": {
    "range": {
      "description": "A1 notation range to read",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "Sheet1!A1:D20"
      ]
    },
    "spreadsheet_id": {
      "description": "Provider spreadsheet identifier",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms"
      ]
    }
  },
  "required": [
    "spreadsheet_id",
    "range"
  ],
  "additionalProperties": false
}`

// Spreadsheet_Range_Read is the argument struct for the Spreadsheet_Range_Read capability.
// Read a cell range from a spreadsheet; returns raw values only, no formatting
type Spreadsheet_Range_Read struct {
	SpreadsheetId string `json:"spreadsheet_id"` // Provider spreadsheet identifier
	Range         string `json:"range"`          // A1 notation range to read
}

// Spreadsheet_Range_UpdateSchema is the JSON Schema for Spreadsheet_Range_Update.
const Spreadsheet_Range_UpdateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Spreadsheet_Range_Update",
  "description": "Write values to a cell range in a spreadsheet",
  "type": "object",
  "properties": {
    "range": {
      "description": "A1 notation range to update",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "Sheet1!A2:C2"
      ]
    },
    "spreadsheet_id": {
      "description": "Provider spreadsheet identifier",
      "type": "string",
      "additionalProperties": false
    },
    "values": {
      "description": "2D array of values to write",
      "type": "array",
      "additionalProperties": false
    }
  },
  "required": [
    "spreadsheet_id",
    "range",
    "values"
  ],
  "additionalProperties": false
}`

// Spreadsheet_Range_Update is the argument struct for the Spreadsheet_Range_Update capability.
// Write values to a cell range in a spreadsheet
type Spreadsheet_Range_Update struct {
	SpreadsheetId string     `json:"spreadsheet_id"` // Provider spreadsheet identifier
	Range         string     `json:"range"`          // A1 notation range to update
	Values        [][]string `json:"values"`         // 2D array of values to write
}

// Spreadsheet_Row_CreateSchema is the JSON Schema for Spreadsheet_Row_Create.
const Spreadsheet_Row_CreateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Spreadsheet_Row_Create",
  "description": "Append a row to the end of a sheet",
  "type": "object",
  "properties": {
    "sheet_name": {
      "description": "Name of the sheet tab to append to",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "Leads"
      ]
    },
    "spreadsheet_id": {
      "description": "Provider spreadsheet identifier",
      "type": "string",
      "additionalProperties": false
    },
    "values": {
      "description": "Ordered list of cell values for the new row",
      "type": "array",
      "additionalProperties": false
    }
  },
  "required": [
    "spreadsheet_id",
    "sheet_name",
    "values"
  ],
  "additionalProperties": false
}`

// Spreadsheet_Row_Create is the argument struct for the Spreadsheet_Row_Create capability.
// Append a row to the end of a sheet
type Spreadsheet_Row_Create struct {
	SpreadsheetId string   `json:"spreadsheet_id"` // Provider spreadsheet identifier
	SheetName     string   `json:"sheet_name"`     // Name of the sheet tab to append to
	Values        []string `json:"values"`         // Ordered list of cell values for the new row
}

// Spreadsheet_Sheet_ListSchema is the JSON Schema for Spreadsheet_Sheet_List.
const Spreadsheet_Sheet_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Spreadsheet_Sheet_List",
  "description": "List all sheet tabs within a spreadsheet",
  "type": "object",
  "properties": {
    "spreadsheet_id": {
      "description": "Provider spreadsheet identifier",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "spreadsheet_id"
  ],
  "additionalProperties": false
}`

// Spreadsheet_Sheet_List is the argument struct for the Spreadsheet_Sheet_List capability.
// List all sheet tabs within a spreadsheet
type Spreadsheet_Sheet_List struct {
	SpreadsheetId string `json:"spreadsheet_id"` // Provider spreadsheet identifier
}

// Swarm_Agent_ListSchema is the JSON Schema for Swarm_Agent_List.
const Swarm_Agent_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Swarm_Agent_List",
  "description": "List agents currently registered with keeperd",
  "type": "object",
  "additionalProperties": false
}`

// Swarm_Agent_List is the argument struct for the Swarm_Agent_List capability.
// List agents currently registered with keeperd
type Swarm_Agent_List struct {
}

// Swarm_Group_SendSchema is the JSON Schema for Swarm_Group_Send.
const Swarm_Group_SendSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Swarm_Group_Send",
  "description": "Send a multicast MUS message to all agents in a named group",
  "type": "object",
  "properties": {
    "group": {
      "description": "Group name as defined in orchestrator.kdl swarm.groups",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "researchers"
      ]
    },
    "msg_type": {
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "task",
        "result",
        "query",
        "ack",
        "error"
      ],
      "default": "task"
    },
    "payload": {
      "description": "Message body to deliver to all group members",
      "type": "string",
      "additionalProperties": false
    }
  },
  "required": [
    "group",
    "payload"
  ],
  "additionalProperties": false
}`

// Swarm_Group_Send is the argument struct for the Swarm_Group_Send capability.
// Send a multicast MUS message to all agents in a named group
type Swarm_Group_Send struct {
	Group   string `json:"group"`   // Group name as defined in orchestrator.kdl swarm.groups
	Payload string `json:"payload"` // Message body to deliver to all group members
	MsgType string `json:"msg_type,omitempty"`
}

// Swarm_Message_SendSchema is the JSON Schema for Swarm_Message_Send.
const Swarm_Message_SendSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Swarm_Message_Send",
  "description": "Send a unicast MUS message to a specific agent via the keeperd switchboard",
  "type": "object",
  "properties": {
    "msg_type": {
      "description": "Semantic message type for the receiver to route on",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "task",
        "result",
        "query",
        "ack",
        "error"
      ],
      "default": "task"
    },
    "payload": {
      "description": "Message body; typically a JSON task description or result",
      "type": "string",
      "additionalProperties": false
    },
    "to_id": {
      "description": "Target agent ID as registered in keeperd",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "researcher-02"
      ]
    }
  },
  "required": [
    "to_id",
    "payload"
  ],
  "additionalProperties": false
}`

// Swarm_Message_Send is the argument struct for the Swarm_Message_Send capability.
// Send a unicast MUS message to a specific agent via the keeperd switchboard
type Swarm_Message_Send struct {
	ToId    string `json:"to_id"`              // Target agent ID as registered in keeperd
	Payload string `json:"payload"`            // Message body; typically a JSON task description or result
	MsgType string `json:"msg_type,omitempty"` // Semantic message type for the receiver to route on
}

// System_Process_ExecSchema is the JSON Schema for System_Process_Exec.
const System_Process_ExecSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "System_Process_Exec",
  "description": "Execute a process in the agent jail and capture its output",
  "type": "object",
  "properties": {
    "command": {
      "description": "Command and arguments as a single string",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "go build ./..."
      ]
    },
    "env": {
      "description": "Additional environment variables as {key, value} objects",
      "type": "array",
      "additionalProperties": false
    },
    "timeout": {
      "description": "Maximum execution time in seconds",
      "type": "integer",
      "additionalProperties": false,
      "default": 60
    },
    "workdir": {
      "description": "Workspace-relative working directory for the process",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "required": [
    "command"
  ],
  "additionalProperties": false
}`

// System_Process_Exec is the argument struct for the System_Process_Exec capability.
// Execute a process in the agent jail and capture its output
type System_Process_Exec struct {
	Command string            `json:"command"`           // Command and arguments as a single string
	Workdir string            `json:"workdir,omitempty"` // Workspace-relative working directory for the process
	Timeout int               `json:"timeout,omitempty"` // Maximum execution time in seconds
	Env     []json.RawMessage `json:"env,omitempty"`     // Additional environment variables as {key, value} objects
}

// System_Process_KillSchema is the JSON Schema for System_Process_Kill.
const System_Process_KillSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "System_Process_Kill",
  "description": "Send a signal to a process in the agent jail",
  "type": "object",
  "properties": {
    "pid": {
      "description": "PID of the process to signal",
      "type": "integer",
      "additionalProperties": false
    },
    "signal": {
      "description": "Signal to send",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "SIGTERM",
        "SIGKILL",
        "SIGINT",
        "SIGHUP"
      ],
      "default": "SIGTERM"
    }
  },
  "required": [
    "pid"
  ],
  "additionalProperties": false
}`

// System_Process_Kill is the argument struct for the System_Process_Kill capability.
// Send a signal to a process in the agent jail
type System_Process_Kill struct {
	Pid    int    `json:"pid"`              // PID of the process to signal
	Signal string `json:"signal,omitempty"` // Signal to send
}

// System_Process_ListSchema is the JSON Schema for System_Process_List.
const System_Process_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "System_Process_List",
  "description": "List running processes in the agent jail",
  "type": "object",
  "additionalProperties": false
}`

// System_Process_List is the argument struct for the System_Process_List capability.
// List running processes in the agent jail
type System_Process_List struct {
}

// VersionControl_Branch_CreateSchema is the JSON Schema for VersionControl_Branch_Create.
const VersionControl_Branch_CreateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VersionControl_Branch_Create",
  "description": "Create and check out a new branch",
  "type": "object",
  "properties": {
    "from": {
      "description": "Ref to branch from",
      "type": "string",
      "additionalProperties": false,
      "default": "HEAD"
    },
    "name": {
      "description": "Name of the new branch",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "feature/add-oauth"
      ]
    },
    "path": {
      "description": "Workspace-relative repository root",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "required": [
    "name"
  ],
  "additionalProperties": false
}`

// VersionControl_Branch_Create is the argument struct for the VersionControl_Branch_Create capability.
// Create and check out a new branch
type VersionControl_Branch_Create struct {
	Path string `json:"path,omitempty"` // Workspace-relative repository root
	Name string `json:"name"`           // Name of the new branch
	From string `json:"from,omitempty"` // Ref to branch from
}

// VersionControl_Branch_ListSchema is the JSON Schema for VersionControl_Branch_List.
const VersionControl_Branch_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VersionControl_Branch_List",
  "description": "List branches in a repository",
  "type": "object",
  "properties": {
    "path": {
      "description": "Workspace-relative repository root",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    },
    "remote": {
      "description": "Include remote-tracking branches",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    }
  },
  "additionalProperties": false
}`

// VersionControl_Branch_List is the argument struct for the VersionControl_Branch_List capability.
// List branches in a repository
type VersionControl_Branch_List struct {
	Path   string `json:"path,omitempty"`   // Workspace-relative repository root
	Remote bool   `json:"remote,omitempty"` // Include remote-tracking branches
}

// VersionControl_Commit_CreateSchema is the JSON Schema for VersionControl_Commit_Create.
const VersionControl_Commit_CreateSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VersionControl_Commit_Create",
  "description": "Stage specified files and create a commit",
  "type": "object",
  "properties": {
    "files": {
      "description": "Workspace-relative file paths to stage; use [\".\"] to stage all changes",
      "type": "array",
      "additionalProperties": false
    },
    "message": {
      "description": "Commit message",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "feat: add OAuth token refresh"
      ]
    },
    "path": {
      "description": "Workspace-relative repository root",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "required": [
    "message",
    "files"
  ],
  "additionalProperties": false
}`

// VersionControl_Commit_Create is the argument struct for the VersionControl_Commit_Create capability.
// Stage specified files and create a commit
type VersionControl_Commit_Create struct {
	Path    string   `json:"path,omitempty"` // Workspace-relative repository root
	Message string   `json:"message"`        // Commit message
	Files   []string `json:"files"`          // Workspace-relative file paths to stage; use ["."] to stage all changes
}

// VersionControl_Diff_ReadSchema is the JSON Schema for VersionControl_Diff_Read.
const VersionControl_Diff_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VersionControl_Diff_Read",
  "description": "Read the diff for staged changes, unstaged changes, or between refs",
  "type": "object",
  "properties": {
    "base": {
      "description": "Base ref for comparison; omit for working-tree diff",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "main"
      ]
    },
    "head": {
      "description": "Head ref for comparison; omit for working-tree diff",
      "type": "string",
      "additionalProperties": false,
      "examples": [
        "feature/my-branch"
      ]
    },
    "path": {
      "description": "Workspace-relative repository root",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "additionalProperties": false
}`

// VersionControl_Diff_Read is the argument struct for the VersionControl_Diff_Read capability.
// Read the diff for staged changes, unstaged changes, or between refs
type VersionControl_Diff_Read struct {
	Path string `json:"path,omitempty"` // Workspace-relative repository root
	Base string `json:"base,omitempty"` // Base ref for comparison; omit for working-tree diff
	Head string `json:"head,omitempty"` // Head ref for comparison; omit for working-tree diff
}

// VersionControl_Log_ListSchema is the JSON Schema for VersionControl_Log_List.
const VersionControl_Log_ListSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VersionControl_Log_List",
  "description": "List recent commits on the current or specified branch",
  "type": "object",
  "properties": {
    "branch": {
      "description": "Branch to list commits from; defaults to current branch",
      "type": "string",
      "additionalProperties": false
    },
    "max_results": {
      "type": "integer",
      "additionalProperties": false,
      "default": 20
    },
    "path": {
      "description": "Workspace-relative repository root",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "additionalProperties": false
}`

// VersionControl_Log_List is the argument struct for the VersionControl_Log_List capability.
// List recent commits on the current or specified branch
type VersionControl_Log_List struct {
	Path       string `json:"path,omitempty"` // Workspace-relative repository root
	MaxResults int    `json:"max_results,omitempty"`
	Branch     string `json:"branch,omitempty"` // Branch to list commits from; defaults to current branch
}

// VersionControl_Remote_PushSchema is the JSON Schema for VersionControl_Remote_Push.
const VersionControl_Remote_PushSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VersionControl_Remote_Push",
  "description": "Push the current branch to a permitted remote",
  "type": "object",
  "properties": {
    "force": {
      "description": "Force push; only permitted if agent.kdl explicitly allows it",
      "type": "boolean",
      "additionalProperties": false,
      "default": false
    },
    "path": {
      "description": "Workspace-relative repository root",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    },
    "remote": {
      "description": "Remote name to push to",
      "type": "string",
      "additionalProperties": false,
      "default": "origin"
    }
  },
  "additionalProperties": false
}`

// VersionControl_Remote_Push is the argument struct for the VersionControl_Remote_Push capability.
// Push the current branch to a permitted remote
type VersionControl_Remote_Push struct {
	Path   string `json:"path,omitempty"`   // Workspace-relative repository root
	Remote string `json:"remote,omitempty"` // Remote name to push to
	Force  bool   `json:"force,omitempty"`  // Force push; only permitted if agent.kdl explicitly allows it
}

// VersionControl_Status_ReadSchema is the JSON Schema for VersionControl_Status_Read.
const VersionControl_Status_ReadSchema = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VersionControl_Status_Read",
  "description": "Read the working tree status of a repository in the agent workspace",
  "type": "object",
  "properties": {
    "path": {
      "description": "Workspace-relative path to the repository root",
      "type": "string",
      "additionalProperties": false,
      "default": "."
    }
  },
  "additionalProperties": false
}`

// VersionControl_Status_Read is the argument struct for the VersionControl_Status_Read capability.
// Read the working tree status of a repository in the agent workspace
type VersionControl_Status_Read struct {
	Path string `json:"path,omitempty"` // Workspace-relative path to the repository root
}
