package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/sblinch/kdl-go"
	"github.com/sblinch/kdl-go/document"
	"github.com/sblinch/kdl-go/relaxed"
)

type kdlCapability struct {
	Name         string
	Category     string
	Description  string
	Risk         string
	Reads        []string
	Writes       []string
	Fields       []kdlField
	Returns      string
	ReturnDesc   string
	ReturnFields []kdlField
}

type kdlField struct {
	Name        string
	Type        string
	Required    bool
	Description string
	Example     string
	Enum        []string
	Default     any
	Min         *float64
	Max         *float64
}

type JSONSchema struct {
	Schema               string                 `json:"$schema,omitempty"`
	Title                string                 `json:"title,omitempty"`
	Description          string                 `json:"description,omitempty"`
	Type                 string                 `json:"type,omitempty"`
	Properties           map[string]*JSONSchema `json:"properties,omitempty"`
	Required             []string               `json:"required,omitempty"`
	AdditionalProperties bool                   `json:"additionalProperties"`
	Enum                 []any                  `json:"enum,omitempty"`
	Default              any                    `json:"default,omitempty"`
	Minimum              *float64               `json:"minimum,omitempty"`
	Maximum              *float64               `json:"maximum,omitempty"`
	Examples             []any                  `json:"examples,omitempty"`
}

func main() {
	dir := flag.String("dir", "capabilities", "directory containing KDL files")
	pkgName := flag.String("pkg", "capabilities", "Go package name for generated code")
	output := flag.String("output", "internal/capabilities/generated.go", "output file name")
	flag.Parse()

	caps, err := loadCapabilities(*dir)
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by vivgen from KDL. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", *pkgName)
	fmt.Fprintf(&buf, "import (\n\t\"bytes\"\n\t\"encoding/base64\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"io\"\n\n\t\"vivary.dev/vivary/pkg/mus\"\n)\n\n")
	fmt.Fprintf(&buf, "type GeneratedField struct {\n")
	fmt.Fprintf(&buf, "\tName string\n")
	fmt.Fprintf(&buf, "\tType string\n")
	fmt.Fprintf(&buf, "\tRequired bool\n")
	fmt.Fprintf(&buf, "\tEnum []string\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "type GeneratedCapabilityInfo struct {\n")
	fmt.Fprintf(&buf, "\tSchema string\n")
	fmt.Fprintf(&buf, "\tFields []GeneratedField\n")
	fmt.Fprintf(&buf, "\tReturnType string\n")
	fmt.Fprintf(&buf, "\tReturnDesc string\n")
	fmt.Fprintf(&buf, "}\n\n")

	// Generate a registry of all capability names and their schemas.
	fmt.Fprintf(&buf, "// GeneratedRegistry returns a map of all registered capability names to their JSON schemas.\n")
	fmt.Fprintf(&buf, "func GeneratedRegistry() map[string]string {\n")
	fmt.Fprintf(&buf, "\treturn map[string]string{\n")
	for _, c := range caps {
		fmt.Fprintf(&buf, "\t\t%q: %sSchema,\n", c.Name, c.Name)
	}
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "// GeneratedCapabilityInfoRegistry returns capability schema metadata used by capwrap and Ward.\n")
	fmt.Fprintf(&buf, "func GeneratedCapabilityInfoRegistry() map[string]GeneratedCapabilityInfo {\n")
	fmt.Fprintf(&buf, "\treturn map[string]GeneratedCapabilityInfo{\n")
	for _, c := range caps {
		fmt.Fprintf(&buf, "\t\t%q: {Schema: %sSchema, Fields: []GeneratedField{", c.Name, c.Name)
		for _, f := range c.Fields {
			fmt.Fprintf(&buf, "{Name: %q, Type: %q, Required: %t, Enum: %#v},", f.Name, f.Type, f.Required, f.Enum)
		}
		fmt.Fprintf(&buf, "}, ReturnType: %q, ReturnDesc: %q},\n", c.Returns, c.ReturnDesc)
	}
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "// NewArgumentPayload constructs a typed MUS payload for a capability's arguments.\n")
	fmt.Fprintf(&buf, "func NewArgumentPayload(name string) (interface{ MarshalMUS() []byte; UnmarshalMUS(io.Reader) error }, bool) {\n")
	fmt.Fprintf(&buf, "\tswitch name {\n")
	for _, c := range caps {
		fmt.Fprintf(&buf, "\tcase %q:\n\t\treturn &%s{}, true\n", c.Name, c.Name)
	}
	fmt.Fprintf(&buf, "\tdefault:\n\t\treturn nil, false\n\t}\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "// NewResultPayload constructs a typed MUS payload for a capability result when the return metadata is structured enough to generate one.\n")
	fmt.Fprintf(&buf, "func NewResultPayload(name string) (interface{ MarshalMUS() []byte; UnmarshalMUS(io.Reader) error }, bool) {\n")
	fmt.Fprintf(&buf, "\tswitch name {\n")
	for _, c := range caps {
		if generatedResultSupported(c) {
			fmt.Fprintf(&buf, "\tcase %q:\n\t\treturn &%s_Result{}, true\n", c.Name, c.Name)
		}
	}
	fmt.Fprintf(&buf, "\tdefault:\n\t\treturn nil, false\n\t}\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "// DecodeResultToJSON decodes a capability result payload into JSON for operator-facing rendering.\n")
	fmt.Fprintf(&buf, "func DecodeResultToJSON(name string, data []byte) ([]byte, bool, error) {\n")
	fmt.Fprintf(&buf, "\tinfo, ok := GeneratedCapabilityInfoRegistry()[name]\n")
	fmt.Fprintf(&buf, "\tif !ok { return nil, false, nil }\n")
	fmt.Fprintf(&buf, "\tswitch info.ReturnType {\n")
	fmt.Fprintf(&buf, "\tcase \"string\":\n\t\tv, err := mus.ReadString(bytes.NewReader(data), mus.MaxPayloadBytes)\n\t\tif err != nil { return nil, false, err }\n\t\tjb, err := json.Marshal(v)\n\t\treturn jb, true, err\n")
	fmt.Fprintf(&buf, "\tcase \"bool\":\n\t\tif len(data) != 1 { return nil, false, fmt.Errorf(\"bool result: expected 1 byte, got %%d\", len(data)) }\n\t\tjb, err := json.Marshal(data[0] != 0)\n\t\treturn jb, true, err\n")
	fmt.Fprintf(&buf, "\tcase \"bytes\":\n\t\tjb, err := json.Marshal(base64.StdEncoding.EncodeToString(data))\n\t\treturn jb, true, err\n")
	fmt.Fprintf(&buf, "\tcase \"list<list<string>>\":\n\t\tv, err := decodeStringMatrix(data)\n\t\tif err != nil { return nil, false, err }\n\t\tjb, err := json.Marshal(v)\n\t\treturn jb, true, err\n")
	fmt.Fprintf(&buf, "\tdefault:\n\t\tpayload, ok := NewResultPayload(name)\n\t\tif !ok { return nil, false, nil }\n\t\tif err := payload.UnmarshalMUS(bytes.NewReader(data)); err != nil { return nil, false, err }\n\t\tjb, err := json.Marshal(payload)\n\t\treturn jb, true, err\n\t}\n}\n\n")
	fmt.Fprintf(&buf, "func decodeStringMatrix(data []byte) ([][]string, error) {\n\tr := bytes.NewReader(data)\n\trowsN, err := mus.ReadVarint(r)\n\tif err != nil { return nil, err }\n\trows := make([][]string, rowsN)\n\tfor i := uint64(0); i < rowsN; i++ {\n\t\tcolsN, err := mus.ReadVarint(r)\n\t\tif err != nil { return nil, err }\n\t\trows[i] = make([]string, colsN)\n\t\tfor j := uint64(0); j < colsN; j++ {\n\t\t\trows[i][j], err = mus.ReadString(r, mus.MaxPayloadBytes)\n\t\t\tif err != nil { return nil, err }\n\t\t}\n\t}\n\tif r.Len() != 0 { return nil, fmt.Errorf(\"string matrix result: trailing payload bytes\") }\n\treturn rows, nil\n}\n\n")

	for _, c := range caps {
		schema := generateSchemaForCapability(c)
		schemaJSON, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			log.Fatal(err)
		}

		fmt.Fprintf(&buf, "// %sSchema is the JSON Schema for %s.\n", c.Name, c.Name)
		fmt.Fprintf(&buf, "const %sSchema = `%s`\n\n", c.Name, string(schemaJSON))

		fmt.Fprintf(&buf, "// %s is the argument struct for the %s capability.\n", c.Name, c.Name)
		if c.Description != "" {
			fmt.Fprintf(&buf, "// %s\n", c.Description)
		}
		fmt.Fprintf(&buf, "type %s struct {\n", c.Name)
		for _, f := range c.Fields {
			goType := kdlTypeToGoType(f.Type)
			jsonTag := f.Name
			if !f.Required {
				jsonTag += ",omitempty"
			}
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`", snakeToPascal(f.Name), goType, jsonTag)
			if f.Description != "" {
				fmt.Fprintf(&buf, " // %s", f.Description)
			}
			fmt.Fprintln(&buf)
		}
		fmt.Fprintf(&buf, "}\n\n")

		// Generate MarshalMUS
		fmt.Fprintf(&buf, "// MarshalMUS serialises %s into binary MUS format.\n", c.Name)
		fmt.Fprintf(&buf, "func (a *%s) MarshalMUS() []byte {\n", c.Name)
		fmt.Fprintf(&buf, "\tvar b []byte\n")
		for _, f := range c.Fields {
			fieldName := snakeToPascal(f.Name)
			switch {
			case f.Type == "string":
				fmt.Fprintf(&buf, "\tb = mus.AppendString(b, a.%s)\n", fieldName)
			case f.Type == "int" || f.Type == "integer":
				fmt.Fprintf(&buf, "\tb = mus.AppendVarint(b, uint64(a.%s))\n", fieldName)
			case f.Type == "bool" || f.Type == "boolean":
				fmt.Fprintf(&buf, "\tif a.%s { b = append(b, 1) } else { b = append(b, 0) }\n", fieldName)
			case f.Type == "object":
				fmt.Fprintf(&buf, "\tb = mus.AppendString(b, string(a.%s))\n", fieldName)
			case strings.HasPrefix(f.Type, "list<"):
				innerType := f.Type[5 : len(f.Type)-1]
				fmt.Fprintf(&buf, "\tb = mus.AppendVarint(b, uint64(len(a.%s)))\n", fieldName)
				fmt.Fprintf(&buf, "\tfor _, v := range a.%s {\n", fieldName)
				switch innerType {
				case "string":
					fmt.Fprintf(&buf, "\t\tb = mus.AppendString(b, v)\n")
				case "object":
					fmt.Fprintf(&buf, "\t\tb = mus.AppendString(b, string(v))\n")
				case "list<string>":
					fmt.Fprintf(&buf, "\t\tb = mus.AppendVarint(b, uint64(len(v)))\n")
					fmt.Fprintf(&buf, "\t\tfor _, vv := range v {\n\t\t\tb = mus.AppendString(b, vv)\n\t\t}\n")
				default:
					fmt.Fprintf(&buf, "\t\t_ = v // TODO: support list<%s>\n", innerType)
				}
				fmt.Fprintf(&buf, "\t}\n")
			default:
				fmt.Fprintf(&buf, "\t_ = a.%s // TODO: support %s\n", fieldName, f.Type)
			}
		}
		fmt.Fprintf(&buf, "\treturn b\n")
		fmt.Fprintf(&buf, "}\n\n")

		// Generate UnmarshalMUS
		fmt.Fprintf(&buf, "// UnmarshalMUS deserialises %s from binary MUS format.\n", c.Name)
		fmt.Fprintf(&buf, "func (a *%s) UnmarshalMUS(r io.Reader) error {\n", c.Name)
		if len(c.Fields) > 0 {
			fmt.Fprintf(&buf, "\tvar err error\n\t_ = err\n")
		}
		for _, f := range c.Fields {
			fieldName := snakeToPascal(f.Name)
			switch {
			case f.Type == "string":
				fmt.Fprintf(&buf, "\tif a.%s, err = mus.ReadString(r, mus.MaxPayloadBytes); err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }\n", fieldName, f.Name)
			case f.Type == "int" || f.Type == "integer":
				fmt.Fprintf(&buf, "\t{ v, err := mus.ReadVarint(r); if err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }; a.%s = int(v) }\n", f.Name, fieldName)
			case f.Type == "bool" || f.Type == "boolean":
				fmt.Fprintf(&buf, "\t{ var b [1]byte; if _, err := io.ReadFull(r, b[:]); err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }; a.%s = b[0] != 0 }\n", f.Name, fieldName)
			case f.Type == "object":
				fmt.Fprintf(&buf, "\t{ s, err := mus.ReadString(r, mus.MaxPayloadBytes); if err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }; a.%s = json.RawMessage(s) }\n", f.Name, fieldName)
			case strings.HasPrefix(f.Type, "list<"):
				innerType := f.Type[5 : len(f.Type)-1]
				fmt.Fprintf(&buf, "\t{ n, err := mus.ReadVarint(r); if err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }; a.%s = make([]%s, n); for i := uint64(0); i < n; i++ {\n", f.Name, fieldName, kdlTypeToGoType(innerType))
				switch innerType {
				case "string":
					fmt.Fprintf(&buf, "\t\tif a.%s[i], err = mus.ReadString(r, mus.MaxPayloadBytes); err != nil { return fmt.Errorf(\"%%s[%%d]: %%w\", %q, i, err) }\n", fieldName, f.Name)
				case "object":
					fmt.Fprintf(&buf, "\t\t{ s, err := mus.ReadString(r, mus.MaxPayloadBytes); if err != nil { return fmt.Errorf(\"%%s[%%d]: %%w\", %q, i, err) }; a.%s[i] = json.RawMessage(s) }\n", f.Name, fieldName)
				case "list<string>":
					fmt.Fprintf(&buf, "\t\t{ m, err := mus.ReadVarint(r); if err != nil { return fmt.Errorf(\"%%s[%%d]: %%w\", %q, i, err) }; a.%s[i] = make([]string, m); for j := uint64(0); j < m; j++ { if a.%s[i][j], err = mus.ReadString(r, mus.MaxPayloadBytes); err != nil { return fmt.Errorf(\"%%s[%%d][%%d]: %%w\", %q, i, j, err) } } }\n", f.Name, fieldName, fieldName, f.Name)
				}
				fmt.Fprintf(&buf, "\t}}\n")
			}
		}
		fmt.Fprintf(&buf, "\treturn nil\n")
		fmt.Fprintf(&buf, "}\n\n")

		if generatedResultSupported(c) {
			emitResultTypes(&buf, c)
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("format error: %v\n---\n%s\n---", err, buf.String())
		log.Fatal(err)
	}

	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
}

func loadCapabilities(dir string) ([]kdlCapability, error) {
	path := filepath.Join(dir, "capabilities.kdl")
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	raw, err := io.ReadAll(f)
	if err != nil {
		return nil, err
	}

	doc, err := kdl.ParseWithOptions(bytes.NewReader(normalizeKDLGenerics(raw)), kdl.ParseOptions{RelaxedNonCompliant: relaxed.NGINXSyntax})
	if err != nil {
		return nil, err
	}

	var caps []kdlCapability
	for _, node := range doc.Nodes {
		if nodeName(node) != "capability" {
			continue
		}
		cap := kdlCapability{Name: firstArg(node)}
		for _, child := range node.Children {
			switch nodeName(child) {
			case "category":
				cap.Category = firstArg(child)
			case "description":
				cap.Description = firstArg(child)
			case "risk":
				cap.Risk = firstArg(child)
			case "reads":
				cap.Reads = append(cap.Reads, propValue(child, "entity"))
			case "writes":
				cap.Writes = append(cap.Writes, propValue(child, "entity"))
			case "field":
				f := kdlField{
					Name:        firstArg(child),
					Type:        propValue(child, "type"),
					Required:    propValueBool(child, "required"),
					Description: childValue(child, "description"),
				}
				if v, ok := child.Properties.Get("default"); ok {
					f.Default = v.Value
				}
				if v, ok := child.Properties.Get("min"); ok {
					if fv, ok := v.Value.(float64); ok {
						f.Min = &fv
					} else if iv, ok := v.Value.(int64); ok {
						fv := float64(iv)
						f.Min = &fv
					}
				}
				if v, ok := child.Properties.Get("max"); ok {
					if fv, ok := v.Value.(float64); ok {
						f.Max = &fv
					} else if iv, ok := v.Value.(int64); ok {
						fv := float64(iv)
						f.Max = &fv
					}
				}
				for _, gc := range child.Children {
					switch nodeName(gc) {
					case "example":
						f.Example = firstArg(gc)
					case "enum":
						for _, arg := range gc.Arguments {
							f.Enum = append(f.Enum, arg.ValueString())
						}
					}
				}
				cap.Fields = append(cap.Fields, f)
			case "returns":
				cap.Returns = firstArg(child)
				cap.ReturnDesc = propValue(child, "description")
				for _, gc := range child.Children {
					if nodeName(gc) != "field" {
						continue
					}
					rf := kdlField{
						Name:        firstArg(gc),
						Type:        propValue(gc, "type"),
						Required:    true,
						Description: childValue(gc, "description"),
					}
					for _, rgc := range gc.Children {
						switch nodeName(rgc) {
						case "example":
							rf.Example = firstArg(rgc)
						case "enum":
							for _, arg := range rgc.Arguments {
								rf.Enum = append(rf.Enum, arg.ValueString())
							}
						}
					}
					cap.ReturnFields = append(cap.ReturnFields, rf)
				}
			}
		}
		caps = append(caps, cap)
	}

	sort.Slice(caps, func(i, j int) bool {
		return caps[i].Name < caps[j].Name
	})

	return caps, nil
}

var (
	kdlTypeGenericRE    = regexp.MustCompile(`type=([A-Za-z_][A-Za-z0-9_]*<[^\s{}]+>)`)
	kdlReturnsGenericRE = regexp.MustCompile(`returns\s+([A-Za-z_][A-Za-z0-9_]*<[^\s{}]+>)`)
)

func normalizeKDLGenerics(src []byte) []byte {
	text := string(src)
	text = kdlTypeGenericRE.ReplaceAllString(text, `type="$1"`)
	text = kdlReturnsGenericRE.ReplaceAllString(text, `returns "$1"`)
	return []byte(text)
}

func generateSchemaForCapability(c kdlCapability) *JSONSchema {
	schema := &JSONSchema{
		Schema:               "http://json-schema.org/draft-07/schema#",
		Title:                c.Name,
		Description:          c.Description,
		Type:                 "object",
		Properties:           make(map[string]*JSONSchema),
		AdditionalProperties: false,
	}

	for _, f := range c.Fields {
		fieldSchema := &JSONSchema{
			Description: f.Description,
			Type:        kdlTypeToJSONType(f.Type),
		}
		if f.Example != "" {
			fieldSchema.Examples = []any{f.Example}
		}
		if len(f.Enum) > 0 {
			for _, e := range f.Enum {
				fieldSchema.Enum = append(fieldSchema.Enum, e)
			}
		}
		if f.Default != nil {
			fieldSchema.Default = f.Default
		}
		if f.Min != nil {
			fieldSchema.Minimum = f.Min
		}
		if f.Max != nil {
			fieldSchema.Maximum = f.Max
		}

		schema.Properties[f.Name] = fieldSchema
		if f.Required {
			schema.Required = append(schema.Required, f.Name)
		}
	}

	return schema
}

func kdlTypeToJSONType(t string) string {
	if strings.HasPrefix(t, "list<") {
		return "array"
	}
	switch t {
	case "string":
		return "string"
	case "int", "integer":
		return "integer"
	case "float", "number":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "object":
		return "object"
	default:
		return "string"
	}
}

func kdlTypeToGoType(t string) string {
	if strings.HasPrefix(t, "list<") {
		inner := t[5 : len(t)-1]
		return "[]" + kdlTypeToGoType(inner)
	}
	switch t {
	case "string":
		return "string"
	case "int", "integer":
		return "int"
	case "float", "number":
		return "float64"
	case "bool", "boolean":
		return "bool"
	case "object":
		return "json.RawMessage"
	default:
		return "string"
	}
}

func snakeToPascal(s string) string {
	if s == "url" {
		return "URL"
	}
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "url" {
			parts[i] = "URL"
			continue
		}
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func nodeName(node *document.Node) string {
	if node == nil || node.Name == nil {
		return ""
	}
	return node.Name.ValueString()
}

func firstArg(node *document.Node) string {
	if node == nil || len(node.Arguments) == 0 {
		return ""
	}
	return node.Arguments[0].ValueString()
}

func propValue(node *document.Node, key string) string {
	if node == nil {
		return ""
	}
	v, ok := node.Properties.Get(key)
	if !ok || v == nil {
		return ""
	}
	return v.ValueString()
}

func propValueBool(node *document.Node, key string) bool {
	if node == nil {
		return false
	}
	v, ok := node.Properties.Get(key)
	if !ok || v == nil {
		return false
	}
	if b, ok := v.Value.(bool); ok {
		return b
	}
	return false
}

func childValue(node *document.Node, childName string) string {
	if node == nil {
		return ""
	}
	for _, child := range node.Children {
		if nodeName(child) == childName {
			return firstArg(child)
		}
	}
	return ""
}

func generatedResultSupported(c kdlCapability) bool {
	switch c.Returns {
	case "object", "list<object>":
		return len(c.ReturnFields) > 0
	case "string", "bool", "bytes", "list<list<string>>":
		return false
	default:
		return false
	}
}

func emitResultTypes(buf *bytes.Buffer, c kdlCapability) {
	fields := c.ReturnFields
	if len(fields) == 0 {
		return
	}
	if c.Returns == "object" {
		emitResultStruct(buf, c.Name+"_Result", c.ReturnDesc, fields)
		return
	}
	itemName := c.Name + "_ResultItem"
	emitResultStruct(buf, itemName, c.ReturnDesc, fields)
	fmt.Fprintf(buf, "// %s_Result is the typed MUS result for %s.\n", c.Name, c.Name)
	fmt.Fprintf(buf, "type %s_Result []%s\n\n", c.Name, itemName)
	fmt.Fprintf(buf, "func (a *%s_Result) MarshalMUS() []byte {\n", c.Name)
	fmt.Fprintf(buf, "\tvar b []byte\n\tb = mus.AppendVarint(b, uint64(len(*a)))\n\tfor i := range *a {\n\t\tb = append(b, (*a)[i].MarshalMUS()...)\n\t}\n\treturn b\n}\n\n")
	fmt.Fprintf(buf, "func (a *%s_Result) UnmarshalMUS(r io.Reader) error {\n", c.Name)
	fmt.Fprintf(buf, "\tn, err := mus.ReadVarint(r)\n\tif err != nil { return err }\n\t*a = make([]%s, n)\n\tfor i := uint64(0); i < n; i++ {\n\t\tif err := (*a)[i].UnmarshalMUS(r); err != nil { return err }\n\t}\n\treturn nil\n}\n\n", itemName)
}

func emitResultStruct(buf *bytes.Buffer, typeName, desc string, fields []kdlField) {
	fmt.Fprintf(buf, "// %s is the typed MUS result payload.\n", typeName)
	if desc != "" {
		fmt.Fprintf(buf, "// %s\n", desc)
	}
	fmt.Fprintf(buf, "type %s struct {\n", typeName)
	for _, f := range fields {
		fmt.Fprintf(buf, "\t%s %s `json:\"%s\"`\n", snakeToPascal(f.Name), kdlTypeToGoType(f.Type), f.Name)
	}
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *%s) MarshalMUS() []byte {\n", typeName)
	fmt.Fprintf(buf, "\tvar b []byte\n")
	for _, f := range fields {
		emitMarshalForField(buf, snakeToPascal(f.Name), f.Type)
	}
	fmt.Fprintf(buf, "\treturn b\n}\n\n")
	fmt.Fprintf(buf, "func (a *%s) UnmarshalMUS(r io.Reader) error {\n", typeName)
	fmt.Fprintf(buf, "\tvar err error\n\t_ = err\n")
	for _, f := range fields {
		emitUnmarshalForField(buf, snakeToPascal(f.Name), f.Name, f.Type)
	}
	fmt.Fprintf(buf, "\treturn nil\n}\n\n")
}

func emitMarshalForField(buf *bytes.Buffer, fieldName, typ string) {
	switch typ {
	case "string":
		fmt.Fprintf(buf, "\tb = mus.AppendString(b, a.%s)\n", fieldName)
	case "int", "integer":
		fmt.Fprintf(buf, "\tb = mus.AppendVarint(b, uint64(a.%s))\n", fieldName)
	case "bool", "boolean":
		fmt.Fprintf(buf, "\tif a.%s { b = append(b, 1) } else { b = append(b, 0) }\n", fieldName)
	}
}

func emitUnmarshalForField(buf *bytes.Buffer, fieldName, rawName, typ string) {
	switch typ {
	case "string":
		fmt.Fprintf(buf, "\tif a.%s, err = mus.ReadString(r, mus.MaxPayloadBytes); err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }\n", fieldName, rawName)
	case "int", "integer":
		fmt.Fprintf(buf, "\t{ v, err := mus.ReadVarint(r); if err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }; a.%s = int(v) }\n", rawName, fieldName)
	case "bool", "boolean":
		fmt.Fprintf(buf, "\t{ var b [1]byte; if _, err := io.ReadFull(r, b[:]); err != nil { return fmt.Errorf(\"%%s: %%w\", %q, err) }; a.%s = b[0] != 0 }\n", rawName, fieldName)
	}
}
