package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sblinch/kdl-go"
	"github.com/sblinch/kdl-go/document"
	"github.com/sblinch/kdl-go/relaxed"
)

type kdlCapability struct {
	Name        string
	Category    string
	Description string
	Risk        string
	Reads       []string
	Writes      []string
	Fields      []kdlField
	Returns     string
	ReturnDesc  string
}

type kdlField struct {
	Name        string
	Type        string
	Required    bool
	Description string
	Example     string
	Enum        []string
	Default     any
	Min         *float64
	Max         *float64
}

type JSONSchema struct {
	Schema               string                 `json:"$schema,omitempty"`
	Title                string                 `json:"title,omitempty"`
	Description          string                 `json:"description,omitempty"`
	Type                 string                 `json:"type,omitempty"`
	Properties           map[string]*JSONSchema `json:"properties,omitempty"`
	Required             []string               `json:"required,omitempty"`
	AdditionalProperties bool                   `json:"additionalProperties"`
	Enum                 []any                  `json:"enum,omitempty"`
	Default              any                    `json:"default,omitempty"`
	Minimum              *float64               `json:"minimum,omitempty"`
	Maximum              *float64               `json:"maximum,omitempty"`
	Examples             []any                  `json:"examples,omitempty"`
}

func main() {
	dir := flag.String("dir", "capabilities", "directory containing KDL files")
	pkgName := flag.String("pkg", "capabilities", "Go package name for generated code")
	output := flag.String("output", "internal/capabilities/generated.go", "output file name")
	flag.Parse()

	caps, err := loadCapabilities(*dir)
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by vivgen from KDL. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", *pkgName)
	fmt.Fprintf(&buf, "import \"encoding/json\"\n\n")

	// Generate a registry of all capability names and their schemas.
	fmt.Fprintf(&buf, "// GeneratedRegistry returns a map of all registered capability names to their JSON schemas.\n")
	fmt.Fprintf(&buf, "func GeneratedRegistry() map[string]string {\n")
	fmt.Fprintf(&buf, "\treturn map[string]string{\n")
	for _, c := range caps {
		fmt.Fprintf(&buf, "\t\t%q: %sSchema,\n", c.Name, c.Name)
	}
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "}\n\n")

	for _, c := range caps {
		schema := generateSchemaForCapability(c)
		schemaJSON, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			log.Fatal(err)
		}

		fmt.Fprintf(&buf, "// %sSchema is the JSON Schema for %s.\n", c.Name, c.Name)
		fmt.Fprintf(&buf, "const %sSchema = `%s`\n\n", c.Name, string(schemaJSON))

		fmt.Fprintf(&buf, "// %s is the argument struct for the %s capability.\n", c.Name, c.Name)
		if c.Description != "" {
			fmt.Fprintf(&buf, "// %s\n", c.Description)
		}
		fmt.Fprintf(&buf, "type %s struct {\n", c.Name)
		for _, f := range c.Fields {
			goType := kdlTypeToGoType(f.Type)
			jsonTag := f.Name
			if !f.Required {
				jsonTag += ",omitempty"
			}
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`", snakeToPascal(f.Name), goType, jsonTag)
			if f.Description != "" {
				fmt.Fprintf(&buf, " // %s", f.Description)
			}
			fmt.Fprintln(&buf)
		}
		fmt.Fprintf(&buf, "}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("format error: %v\n---\n%s\n---", err, buf.String())
		log.Fatal(err)
	}

	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
}

func loadCapabilities(dir string) ([]kdlCapability, error) {
	path := filepath.Join(dir, "capabilities.kdl")
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	doc, err := kdl.ParseWithOptions(f, kdl.ParseOptions{RelaxedNonCompliant: relaxed.NGINXSyntax})
	if err != nil {
		return nil, err
	}

	var caps []kdlCapability
	for _, node := range doc.Nodes {
		if nodeName(node) != "capability" {
			continue
		}
		cap := kdlCapability{Name: firstArg(node)}
		for _, child := range node.Children {
			switch nodeName(child) {
			case "category":
				cap.Category = firstArg(child)
			case "description":
				cap.Description = firstArg(child)
			case "risk":
				cap.Risk = firstArg(child)
			case "reads":
				cap.Reads = append(cap.Reads, propValue(child, "entity"))
			case "writes":
				cap.Writes = append(cap.Writes, propValue(child, "entity"))
			case "field":
				f := kdlField{
					Name:        firstArg(child),
					Type:        propValue(child, "type"),
					Required:    propValueBool(child, "required"),
					Description: childValue(child, "description"),
				}
				if v, ok := child.Properties.Get("default"); ok {
					f.Default = v.Value
				}
				if v, ok := child.Properties.Get("min"); ok {
					if fv, ok := v.Value.(float64); ok {
						f.Min = &fv
					} else if iv, ok := v.Value.(int64); ok {
						fv := float64(iv)
						f.Min = &fv
					}
				}
				if v, ok := child.Properties.Get("max"); ok {
					if fv, ok := v.Value.(float64); ok {
						f.Max = &fv
					} else if iv, ok := v.Value.(int64); ok {
						fv := float64(iv)
						f.Max = &fv
					}
				}
				for _, gc := range child.Children {
					switch nodeName(gc) {
					case "example":
						f.Example = firstArg(gc)
					case "enum":
						for _, arg := range gc.Arguments {
							f.Enum = append(f.Enum, arg.ValueString())
						}
					}
				}
				cap.Fields = append(cap.Fields, f)
			case "returns":
				cap.Returns = firstArg(child)
				cap.ReturnDesc = propValue(child, "description")
			}
		}
		caps = append(caps, cap)
	}

	sort.Slice(caps, func(i, j int) bool {
		return caps[i].Name < caps[j].Name
	})

	return caps, nil
}

func generateSchemaForCapability(c kdlCapability) *JSONSchema {
	schema := &JSONSchema{
		Schema:               "http://json-schema.org/draft-07/schema#",
		Title:                c.Name,
		Description:          c.Description,
		Type:                 "object",
		Properties:           make(map[string]*JSONSchema),
		AdditionalProperties: false,
	}

	for _, f := range c.Fields {
		fieldSchema := &JSONSchema{
			Description: f.Description,
			Type:        kdlTypeToJSONType(f.Type),
		}
		if f.Example != "" {
			fieldSchema.Examples = []any{f.Example}
		}
		if len(f.Enum) > 0 {
			for _, e := range f.Enum {
				fieldSchema.Enum = append(fieldSchema.Enum, e)
			}
		}
		if f.Default != nil {
			fieldSchema.Default = f.Default
		}
		if f.Min != nil {
			fieldSchema.Minimum = f.Min
		}
		if f.Max != nil {
			fieldSchema.Maximum = f.Max
		}

		schema.Properties[f.Name] = fieldSchema
		if f.Required {
			schema.Required = append(schema.Required, f.Name)
		}
	}

	return schema
}

func kdlTypeToJSONType(t string) string {
	if strings.HasPrefix(t, "list<") {
		return "array"
	}
	switch t {
	case "string":
		return "string"
	case "int", "integer":
		return "integer"
	case "float", "number":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "object":
		return "object"
	default:
		return "string"
	}
}

func kdlTypeToGoType(t string) string {
	if strings.HasPrefix(t, "list<") {
		inner := t[5 : len(t)-1]
		return "[]" + kdlTypeToGoType(inner)
	}
	switch t {
	case "string":
		return "string"
	case "int", "integer":
		return "int"
	case "float", "number":
		return "float64"
	case "bool", "boolean":
		return "bool"
	case "object":
		return "json.RawMessage"
	default:
		return "string"
	}
}

func snakeToPascal(s string) string {
	if s == "url" {
		return "URL"
	}
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "url" {
			parts[i] = "URL"
			continue
		}
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func nodeName(node *document.Node) string {
	if node == nil || node.Name == nil {
		return ""
	}
	return node.Name.ValueString()
}

func firstArg(node *document.Node) string {
	if node == nil || len(node.Arguments) == 0 {
		return ""
	}
	return node.Arguments[0].ValueString()
}

func propValue(node *document.Node, key string) string {
	if node == nil {
		return ""
	}
	v, ok := node.Properties.Get(key)
	if !ok || v == nil {
		return ""
	}
	return v.ValueString()
}

func propValueBool(node *document.Node, key string) bool {
	if node == nil {
		return false
	}
	v, ok := node.Properties.Get(key)
	if !ok || v == nil {
		return false
	}
	if b, ok := v.Value.(bool); ok {
		return b
	}
	return false
}

func childValue(node *document.Node, childName string) string {
	if node == nil {
		return ""
	}
	for _, child := range node.Children {
		if nodeName(child) == childName {
			return firstArg(child)
		}
	}
	return ""
}
